name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 0.1.3)'
        required: true
        type: string
      release_type:
        description: 'Type of release'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: 'patch'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: |
          make setup
          uv pip install -e ".[dev]"
          
      - name: Set version (manual trigger only)
        if: github.event_name == 'workflow_dispatch'
        run: |
          make version-set VERSION=${{ github.event.inputs.version }}
          
      - name: Bump version (manual trigger only)
        if: github.event_name == 'workflow_dispatch'
        run: |
          make version-bump TYPE=${{ github.event.inputs.release_type }}
          
      - name: Build package
        run: |
          make build
          
      - name: Publish to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          make publish
          
      - name: Create git tag (manual trigger only)
        if: github.event_name == 'workflow_dispatch'
        run: |
          VERSION=$(make version)
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add pyproject.toml CHANGELOG.md
          git commit -m "Release $VERSION"
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin main
          git push origin "v$VERSION"
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          body: |
            See the [CHANGELOG](https://github.com/colebrumley/pysumoapi/blob/main/CHANGELOG.md) for details.
          draft: false
          prerelease: false
          generate_release_notes: true 