name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: |
          make setup
          
      - name: Build package
        run: |
          make build
          
      - name: Publish to PyPI
        run: |
          make publish
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          body: |
            See the [CHANGELOG](https://github.com/colebrumley/pysumoapi/blob/main/CHANGELOG.md) for details.
          draft: false
          prerelease: false
          generate_release_notes: true 